language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - compiler: gcc-5
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.4-dev
            - gcc-5
            - g++-5
      env: GCC=5 PYTHON=python3.4
    - compiler: gcc-5
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.5-dev
            - gcc-5
            - g++-5
      env: GCC=5 PYTHON=python3.5
    - compiler: gcc-6
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.4-dev
            - gcc-6
            - g++-6
      env: GCC=6 PYTHON=python3.4
    - compiler: gcc-6
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.5-dev
            - gcc-6
            - g++-6
      env: GCC=6 PYTHON=python3.5
    - compiler: clang-3.9
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            # we install gcc in the clang builds to get an updated libstd++
            - gcc-5
            - g++-5
            - python3.4-dev
            - clang-3.9
      env: CLANG=3.9 PYTHON=python3.4
    - compiler: clang-3.9
      os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            # we install gcc in the clang builds to get an updated libstd++
            - gcc-5
            - g++-5
            - python3.5-dev
            - clang-3.9
      env: CLANG=3.9 PYTHON=python3.5
    - compiler: clang
      os: osx
      osx_image: xcode8.1
      env: PYTHON_VER=3.4.4 PYTHON=python3
    - compiler: clang
      os: osx
      osx_image: xcode8.1
      env: PYTHON_VER=3.5.2 PYTHON=python3

install:
  - source etc/ci-install.sh

before_script:
  - ${CXX} --version
  - ${PYTHON} --version

script:
  - make -j 8 test

notifications:
  email: false
